FROM ruby:latest

# Install Jekyll
RUN gem install jekyll bundler

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./src /app

# build with jekyll
RUN bundle install
RUN bundle exec jekyll build
