name: Jekyll site CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  publish-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Jekyll site and copy to Nginx container
        run: |
          docker run --rm \
            --volume="$PWD/src/:/srv/jekyll" \
            jekyll/jekyll:latest \
            jekyll build

          docker create --name jekyll-site ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-jekyll:latest
          docker cp jekyll-site:/srv/jekyll/_site/ ./_site
          docker rm jekyll-site

      - name: Build and push Docker Nginx image
        run: |
          docker buildx create --use
          docker buildx build \
            --cache-from ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-nginx:latest \
            --tag ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-nginx:latest \
            --platform linux/amd64,linux/arm64 \
            --push \
            --file Dockerfile.nginx . \